"""architecture_refactor_foundation

Revision ID: 98418e82939c
Revises: 60f789dd0ce0
Create Date: 2026-05-11 14:13:56.821106
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98418e82939c'
down_revision: Union[str, None] = '60f789dd0ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('evaluation_score', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('evaluation_summary', sa.Text(), nullable=True))
    op.alter_column('calls', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'twilio'::character varying"))
    op.alter_column('calls', 'voice_runtime',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'openai_realtime'::character varying"))
    op.drop_constraint('interview_questions_resume_id_fkey', 'interview_questions', type_='foreignkey')
    op.drop_column('interview_questions', 'resume_id')
    op.add_column('jobs', sa.Column('evaluation_criteria', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('matching_score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('match_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'match_explanation')
    op.drop_column('resumes', 'matching_score')
    op.drop_column('jobs', 'evaluation_criteria')
    op.add_column('interview_questions', sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('interview_questions_resume_id_fkey', 'interview_questions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.alter_column('calls', 'voice_runtime',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'openai_realtime'::character varying"))
    op.alter_column('calls', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'twilio'::character varying"))
    op.drop_column('calls', 'evaluation_summary')
    op.drop_column('calls', 'evaluation_score')
    # ### end Alembic commands ###
